env:
  browser: true
  commonjs: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - tsconfig.json
  ecmaVersion: latest
rules:
  no-underscore-dangle: 0
  class-methods-use-this: 0
  import/prefer-default-export: 0
  import/extensions:
    - error
    - ignorePackages
    - js: "never"
      ts: "never"
  dot-notation: off
  "@typescript-eslint/dot-notation":
    - "error"
  "@typescript-eslint/lines-between-class-members":
    - error
    - always
    - exceptAfterSingleLine: true
settings:
  import/resolver:
    node:
      extensions:
        - .ts
        - .js
plugins:
  - jest
  - "@typescript-eslint"

