name: Test destructive mode
on:
  push:
    branches:
      - "track/*"
      - "main"
  pull_request:
    branches:
      - "track/*"
      - "main"

jobs:
  build:
    name: Release to edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Preinstall deps
      #   run: |
      #     sudo apt-get update && sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install cargo=0.58.0-0ubuntu1~20.04.1 libstd-rust-1.57=1.57.0+dfsg1+llvm-0ubuntu1~20.04.1 libstd-rust-dev=1.57.0+dfsg1+llvm-0ubuntu1~20.04.1 rustc=1.57.0+dfsg1+llvm-0ubuntu1~20.04.1

      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@1.0.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@1.0.2
        id: channel

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "false"
          channel: "${{ steps.channel.outputs.name }}"
          # charm-path: ./orc8r-certifier-operator

      # - uses: canonical/charmhub-upload-action@0.2.1
      #   with:
      #     credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
      #     charm-path: ./orc8r-certifier-operator
      #     upload-image: "false"

      # - name: Setup SSH upterm session
      #   uses: lhotari/action-upterm@v1

      # - name: Configure LXD
      #   run: |
      #     sudo groupadd --force --system lxd
      #     sudo usermod --append --groups lxd runner
      #     sudo snap start lxd
      #     sudo lxd waitready --timeout=30
      #     sudo lxd init --auto

      # - name: Install charmcraft
      #   run: |
      #     sudo snap install charmcraft --classic

      # - name: Build my Charm
      #   run: |
      #     sg lxd -c "charmcraft -v pack"
