name: GitHub Actions Demo

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  upload_to_charmhub:
    if: ${{ github.event.pull_request.merged }} # Avoids the action from being triggered when the PR is discarded
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }}."
      # - name: Check out repository code
      #   uses: actions/checkout@v2
      # - name: Upload to charmhub
      #   uses: canonical/charmhub-upload-action@0.2.0
      #   with:
      #     credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: my-logs
      #     path: /home/runner/snap/charmcraft/common/cache/charmcraft/log/ # or path/to/artifact
