name: Test destructive mode
on:
  push:
    branches:
      - "track/*"
      - "main"
  pull_request:
    branches:
      - "track/*"
      - "main"

jobs:
  build:
    name: Release to edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@1.0.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@1.0.0
        id: channel

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "true"
          channel: "${{ steps.channel.outputs.name }}"
          charm-path: ./

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: my-logs
      #     path: /home/runner/snap/charmcraft/common/cache/charmcraft/log/ # or path/to/artifact
# name: Test Charmhub Upload

# jobs:
#   test-charmhub-upload:
#     runs-on: ubuntu-latest
#     name: Test charmhub upload
#     steps:
#       - uses: actions/checkout@v2

#       - name: Check libraries
#         uses: ./check-libraries
#         with:
#           credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
#           github-token: "${{ secrets.GITHUB_TOKEN }}"
#           charm-path: test-charm/

#       - name: Select charmhub channel
#         uses: ./channel
#         id: channel

#       - name: Upload charm to charmhub
#         uses: ./upload-charm
#         with:
#           tag-prefix: test-charm
#           credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
#           charm-path: test-charm/
#           upload-image: "true"
#           channel: "${{ steps.channel.outputs.name }}"
#           github-token: "${{ secrets.GITHUB_TOKEN }}"

#       - name: Upload bundle to charmhub
#         uses: ./upload-bundle
#         with:
#           credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
#           bundle-path: test-bundle/
#           github-token: "${{ secrets.GITHUB_TOKEN }}"
