name: GitHub Actions Demo
# change
# on:
#   pull_request:
#     branches:
#       - main
#     types: [closed]
on:
  push:
    branches:
      - main

jobs:
  upload_to_charmhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Upload to charmhub
        uses: ./charmhub-upload-action
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: my-logs
      #     path: /home/runner/snap/charmcraft/common/cache/charmcraft/log/ # or path/to/artifact
